### PR TITLE
lockfile 2

### PR DESCRIPTION
**Pull request by zwhitchcox**
This pr upgrades the lockfile to version 2, a step towards compatibility with Node 16

Change-type: minor

### CODE REVIEW

**Review by mcraa — COMMENTED** [review]
I can flash multiple things with etcher using this branch on windows 👍 
On linux after install the `node_modules/etcher-sdk/build` folder is not present, resulting in `Can't resolve 'etcher-sdk'` errors. I don't know if it is an issue with linux, npm or my config.
Probably won't happen with the published npm version.

**Review by mcraa — APPROVED** [review]

**Comment by mcraa** [comment]
I was too quick @zwhitchcox 
FYI using node 16.x instead of 14 makes it work with the `prepare` script.

**Comment by zwhitchcox** [comment]
Thanks @mcraa Does that mean we should switch back to thundron/lzma-native? I'm not sure if we still need 14 to work though...maybe we could do that later.

**Comment by mcraa** [comment]
no need to go back imo @zwhitchcox,
the 7.2 npm package works fine with 14 or 16,
just for testing/reviewing when I used the git repo directly in the package.json
but it is a nice flag for us to see what needs to be done if we want to keep up with node

**Pull request merged**
