### PR TITLE
Add node-beaglebone-usbboot work on Mac & Linux

### PR DESCRIPTION
**Pull request by parthi-g**
Work on Mac os catalina and ubuntu 18.04 
Node: 12.14.0

### CODE REVIEW

**Comment by zvin** [comment]
Thanks @parthi-g 
I can't merge this as it is as I'm afraid there might be issues in node-beaglebone-usbboot if you plug more than one beaglebone.
I'll work on this when I have some time, hopefully soon.

**Comment by parthi-g** [comment]
Ok @zvin , Thank you for the review.

**Comment by jadonk** [comment]
@zvin any thoughts on how to fix this for more than one BeagleBone?

**Comment by jadonk** [comment]
BTW, what issue would you expect to encounter?

**Comment by shawaj** [comment]
@jadonk @parthi-g I spoke to @zvin briefly about this after our call today. Basically, we just need to ensure that:

1. this works on all platforms that we support ([macOS, Windows, various flavours of Linux](https://www.balena.io/etcher/))
2. this can actually flash multiple devices simultaneously / clone devices

For 2, this hasn't been tested on our side, but based on the code [here](https://github.com/parthi-g/node-beaglebone-usbboot/blob/master/src/index.ts#L127) Alexis thinks this will probably fail. Because of `UsbBBbootScanner.stepCounter` it is suspected it will either not work, or the reported progress will be incorrect.

Hope that helps!

**Comment by parthi-g** [comment]
@shawaj I did not have multiple Beaglebone to test this,I have tested this on single Beaglebone and It was working!

**Comment by zvin** [comment]
replaced by #204

**Pull request closed without merging**
